//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     创建人：wms
//     创建时间：2019/12/11 16:10:46
//     说明：
// </auto-generated>
//------------------------------------------------------------------------------
using JadeFramework.Core.Dapper;
using JadeFramework.WorkFlow;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MsSystem.WF.Model
{
    /// <summary>
    /// 流程委托表
    /// </summary>
    [Table("wf_workflow_assign")]
    public class WfWorkflowAssign : Entity
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public Guid Id { get; set; }

        /// <summary>
        /// 流程id
        /// </summary>
        public Guid FlowId { get; set; }

        /// <summary>
        /// 实例id
        /// </summary>
        public Guid InstanceId { get; set; }

        /// <summary>
        /// 节点id
        /// </summary>
        public Guid NodeId { get; set; }

        /// <summary>
        /// 节点名
        /// </summary>
        public string NodeName { get; set; }

        /// <summary>
        /// 请求人id
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// 请求人姓名
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// 委托人id
        /// </summary>
        public string AssignUserId { get; set; }

        /// <summary>
        /// 委托人姓名
        /// </summary>
        public string AssignUserName { get; set; }

        /// <summary>
        /// 委托信息
        /// </summary>
        public string Content { get; set; }

    }
    public class WfWorkflowAssignMapper : ClassMapper<WfWorkflowAssign>
    {
        public WfWorkflowAssignMapper()
        {
            Table("wf_workflow_assign");
            AutoMap();
        }
    }
}

