//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     创建人：wms
//     创建时间：2019/12/1 14:30:15
//     说明：
// </auto-generated>
//------------------------------------------------------------------------------
using JadeFramework.Dapper;
using MsSystem.WF.Model;

namespace MsSystem.WF.IRepository
{
    /// <summary>
    /// 催办记录表 仓储接口
    /// </summary>
    public interface IWfWorkflowUrgeRepository : IDapperRepository<WfWorkflowUrge>
    {
    }
}

