//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     创建人：wms
//     创建时间：2019/12/11 16:10:49
//     说明：
// </auto-generated>
//------------------------------------------------------------------------------
using JadeFramework.Dapper;
using MsSystem.WF.Model;

namespace MsSystem.WF.IRepository
{
    /// <summary>
    /// 流程委托表 仓储接口
    /// </summary>
    public interface IWfWorkflowAssignRepository : IDapperRepository<WfWorkflowAssign>
    {
    }
}

